### ISSUE TITLE
Missing source files 

### ISSUE THREAD

**Issue by jorabra** [angular-redux/router#4]
Error message when building my application with Webpack 2.2.1 using '@angular-redux/router@6.0.0' and 'source-map-loader@0.1.6':

> WARNING in ./~/@angular-redux/router/lib/esm/index.js
Cannot find source file '../../src/index.ts': Error: Can't resolve '../../src/index.ts' in 'C:\Source\NVT\NHN.NVT.Web\node_modules\@angular-redux\router\lib\esm'
 @ ./src/vendor.ts 13:0-32
 @ ./src/vendor.dynamic.ts
>
> WARNING in ./\~/@angular-redux/router/lib/esm/actions.js
Cannot find source file '../../src/actions.ts': Error: Can't resolve '../../src/actions.ts' in 'C:\Source\NVT\NHN.NVT.Web\node_modules\@angular-redux\router\lib\esm'
 @ ./~/@angular-redux/router/lib/esm/index.js 4:0-44
 @ ./src/vendor.ts
 @ ./src/vendor.dynamic.ts
>
> WARNING in ./\~/@angular-redux/router/lib/esm/reducer.js
Cannot find source file '../../src/reducer.ts': Error: Can't resolve '../../src/reducer.ts' in 'C:\Source\NVT\NHN.NVT.Web\node_modules\@angular-redux\router\lib\esm'
 @ ./~/@angular-redux/router/lib/esm/index.js 3:0-42
 @ ./src/vendor.ts
 @ ./src/vendor.dynamic.ts
>
>WARNING in ./\~/@angular-redux/router/lib/esm/router.js
Cannot find source file '../../src/router.ts': Error: Can't resolve '../../src/router.ts' in 'C:\Source\NVT\NHN.NVT.Web\node_modules\@angular-redux\router\lib\esm'
 @ ./~/@angular-redux/router/lib/esm/index.js 2:0-41
 @ ./src/vendor.ts
 @ ./src/vendor.dynamic.ts

Adding the missing source files would solve this issue I suppose.

**Comment by dagstuan** [comment]
6.0.1 should fix this. Included the source files in the npm package. Let me know if you have further issues :)

**Comment by SethDavenport** [comment]
Is this something I broke with the move? If so sorry about that!

**Comment by dagstuan** [comment]
No this was already broken I think, so no problem :)
