### ISSUE TITLE
'router' state is only ever empty string

### ISSUE THREAD

**Issue by ghost** [angular-redux/router#5]
I have integrated @angular-redux/router according to https://github.com/angular-redux/router readme, but the redux-logger only shows an empty string for the router property all the time?  

My app.module.ts pulls in an AppRoutingModule and I make sure it is imported before NgReduxRouterModule:
```
...
import { NgReduxRouterModule } from '@angular-redux/router';
import { AppRoutingModule } from './app-routing.module';
...
@NgModule({
  declarations: [...],
  imports: [
    ...
    AppRoutingModule,
    NgReduxModule,
    NgReduxRouterModule


```
My app builds and runs but the 'router' slice of the store is only ever an empty string?

**Comment by dagstuan** [comment]
Hello, do you have an example of this? A plnkr or something that I can play with to see what's wrong?

**Comment by ghost** [comment]
I had a different configuration error that caused this problem, so I am closing this issue.
